project:
  type: website
  output-dir: docs
bibliography: references.bib
citation-location: margin

execute:
  freeze: auto  # re-render only when source changes
  
website:
  title: "kiwi-causal-lab"
  navbar:
    search: true
    left:
    - text: "People"
      href: people/people.qmd
    - text: "News"
      href: news/news.qmd
    - text: "Research"
      href: research/research.qmd
    - text: "Publications"
      href: publications/publications.qmd
    - text: "reports"
      href: reports/reports.qmd
    - text: "Resources"
      menu:
        - text: "Software"
          href: resources/software/software.qmd
        - text: "Teaching"
          href: resources/teaching/teaching.qmd

format:
  html:
    theme: lux
    toc: true
    css: styles.css
    html-math-method: katex


license: CC BY-NC-SA
