{
  "hash": "5badce9cc4c5fd54b30ee74eb653e7d6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploring Institutional Trust in New Zealand Pre/Post COVID-19 Pandemic\" \nsubtitle: \"New Zealand Attitudes and Values Study: Years 2019-2022 N = 42,681\"\ndate: 2023-03-23\ndate-format: short\nauthor: \n  - name: Authors TBA\n    affiliation: TBA\n  - name: Chris G Sibley\n    orcid: 0000-0002-4064-8800\n    affiliation: University of Auckland,  New Zealand\n  - name: Joseph Bulbulia\n    orcid: 0000-0002-5861-2056\n    affiliation: Victoria University of Wellington, New Zealand\n    email: joseph.bulbulia@vuw.ac.nz\n    corresponding: yes\ncategories:\n  - NZAVS\n  - COVID\n  - Descriptive\nexecute:\n  warning: false\ndraft: false\nimage: \"trust_science.png\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code\"\nbibliography: references.bib\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n\n## NZAVS Report on Institutional Trust Pre/Post COVID\n\nThis report delves into the changes in institutional trust among New Zealanders from the pre-pandemic period in 2019 to 2022.\n\nThe New Zealand Attitudes and Values Study uses a two-item scale to measure **Trust in Science**\n\n-   \"I have a high degree of confidence in the scientific community.\"[@nisbet2015]\n\n-   \"Our society places too much emphasis on science.\"(reverse coded) \n\nWe average these scores to form a single score [@hartman2017]. ^[We do not blindly adhere to the standard measurement approaches in psychometrics.  It might be preferable to work with single items instead of the averaged score. See [@vanderweele2022] for more information on this point.]\nThese items were introduced in NZAVS Wave 11 (2019 - 2020) ^[We must be cautious: causal identification requires contrasting outcomes under different exposures.  Because all were exposed to the COVID-19 pandemic, these contrasts are not identified without the strong assumption that there were no pre-existing trends in the acceptance of science before the COVID-19 pandemic struck.]\n\nPrevious research using a propensity score design reported on changes in Trust in Science during the first three weeks of New Zealand's COVID lockdown in March and April 2020 [@sibley2020].\n\n**COVID-19 Government response** [@marques2022]\n\n-   \"I trust the Government to make sensible decisions about how to best manage COVID-19 in New Zealand.\"\n-   \"The New Zealand government response to COVID-19.\"\n\n**Trust in politicians** [@sibley2020]\n\n-   \"Politicians in New Zealand can generally be trusted.\"\n\n**Institutional trust in police** [@tyler2005]\n\n-   \"People's basic rights are well protected by the New Zealand Police.\"\n-   \"There are many things about the New Zealand Police and its policies that need to be changed.\"\n-   \"The New Zealand Police care about the well-being of everyone they deal with.\"\n\n**General tendency to believe in conspiracies**[@lantian2016]\n\n-   \"I think that the official version of major world events given by authorities often hides the truth.\"\n\n### Sample responses: years 2019-2020: Pre-Covid, Lockdown, Post-Lockdown\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read data\ndat <- arrow::read_parquet(pull_path)\n\n# sometimes arrow objects give me trouble\ndat <- as.data.frame(dat)\n\n\n# create covid timeline variables, select waves of interest. \ndt <- dat |>\n  data.frame() |>\n# create covid timeline \n mutate(covid_condition = as.factor(ifelse(\n    TSCORE < 3922,\n    \"pre_covid\",\n    ifelse(TSCORE >= 3922 &\n             TSCORE <= 3954, \"lockdown\",\n           \"post_lockdown\")\n  ))) |> \n  mutate(covid_condition = factor(covid_condition, levels = c(\"pre_covid\", \"lockdown\", \"post_lockdown\"))) |> # order levels\n  # select waves\n  dplyr::filter(Wave == 2019| Wave == 2020| Wave == 2021) |>\n    dplyr::filter(\n      (Wave == 2019  &\n         YearMeasured  == 1 & !is.na(covid_condition)) |\n      (Wave == 2020) |\n      (Wave == 2021)) |>  \n  group_by(Id) |> \n  # inclusion criteria, all those who participated in 2019\n  dplyr::mutate(org2019 = ifelse(Wave == 2019 &\n                                   YearMeasured == 1, 1, 0)) |>  # creating an indicator for the first wave\n  dplyr::mutate(hold19 = mean(org2019, na.rm = TRUE)) |>  # Hack\n  dplyr::filter(hold19 > 0) |> # hack to enable repeat of baselin\n  fill(w_GendAgeEuro, .direction = \"down\") |> # weights are all for 2018. Fill if missing\n  ungroup() |>\n  droplevels() |>\n  mutate(time = as.numeric(Wave) - 1) |>\n  arrange(Id, time) |>\n  select(\n    Id,\n    covid_condition,\n    YearMeasured,\n    COVID19.Timeline,\n    w_GendAgeEuro, # survey weights for PATT\n    time,\n    TSCORE,\n    Wave,\n    Partner,\n    Euro,\n    EthCat,\n    GenCohort,\n    # Gender3,\n    Male,\n    SampleFrame,\n    NZSEI13,\n    NZDep2018,\n    Rural_GCH2018,\n    REGC_2022,\n    CONSCIENTIOUSNESS,\n    OPENNESS,\n    HONESTY_HUMILITY,\n    EXTRAVERSION,\n    NEUROTICISM,\n    AGREEABLENESS,\n    edu_n,\n    Employed,\n    BornNZ,\n    Pol.Orient,\n    Pol.Wing,\n    Parent,\n    Relid,\n    SDO,\n    RWA,\n    ConspiracyBeliefs,\n    SCIENCE.TRUST,\n    POLICE.TRUST,\n    COVID.TrustGovtResponse,\n    Pol.PoliticianTrust#,\n  # ScienceTrust01, # individual item\n  # ScienceTrust02r  # individual item\n  ) |> \n  rename(\n  Conspiracy_Beliefs  = ConspiracyBeliefs,\n  Trust_in_Science =  SCIENCE.TRUST,\n  Trust_in_Politicians = Pol.PoliticianTrust,\n  Trust_in_Police = POLICE.TRUST,\n  Trust_in_Govt_Covid_Response = COVID.TrustGovtResponse, \n  ) |> \n  droplevels() |> \n  arrange(Id,Wave)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# this code creates a table\n# function to make tables simple         \n# simplify\nmy.render.cont <- function(x) {\n  with(stats.apply.rounding(stats.default(x), digits=3), c(\"\",\n                                                           \"Mean (SD)\"=sprintf(\"%s (&plusmn; %s)\", MEAN, SD)))\n}\n\nmy.render.cat <- function(x) {\n  c(\"\", sapply(stats.default(x), function(y) with(y,\n                                                  sprintf(\"%d (%0.0f %%)\", FREQ, PCT))))\n}\n\n\n# select only 2019-2021\ndt_19 <-dt |> \n  dplyr::filter(Wave == 2019)\n\n\ntab_19_trust <- table1::table1(\n  ~ Trust_in_Science +\n    Trust_in_Politicians +\n    Trust_in_Police +\n    Conspiracy_Beliefs| covid_condition,\n  data = dt_19,\n  overall = FALSE,\n  render.continuous = my.render.cont,\n  render.categorical = my.render.cat\n)\n\n# needed for markdown tables\ntab_19_trust <- data.frame( tab_19_trust )\n\ntab_19_trust <- tab_19_trust |> \n    rename(\"Forms of Institutional Trust\" = X.)\n\n# show\ntab_19_trust |>\n  kbl(format = \"markdown\", booktabs = TRUE)\n```\n\n::: {.cell-output-display}\n\n\n|Forms of Institutional Trust |pre_covid            |lockdown             |post_lockdown        |\n|:----------------------------|:--------------------|:--------------------|:--------------------|\n|                             |(N=29812)            |(N=3511)             |(N=9358)             |\n|Trust_in_Science             |                     |                     |                     |\n|Mean (SD)                    |5.36 (&plusmn; 1.28) |5.66 (&plusmn; 1.23) |5.55 (&plusmn; 1.27) |\n|Missing                      |289 (1.0%)           |16 (0.5%)            |70 (0.7%)            |\n|Trust_in_Politicians         |                     |                     |                     |\n|Mean (SD)                    |3.72 (&plusmn; 1.44) |4.00 (&plusmn; 1.48) |3.78 (&plusmn; 1.48) |\n|Missing                      |685 (2.3%)           |25 (0.7%)            |143 (1.5%)           |\n|Trust_in_Police              |                     |                     |                     |\n|Mean (SD)                    |4.61 (&plusmn; 1.23) |4.60 (&plusmn; 1.34) |4.50 (&plusmn; 1.33) |\n|Missing                      |12 (0.0%)            |0 (0%)               |3 (0.0%)             |\n|Conspiracy_Beliefs           |                     |                     |                     |\n|Mean (SD)                    |4.38 (&plusmn; 1.60) |4.29 (&plusmn; 1.68) |4.31 (&plusmn; 1.69) |\n|Missing                      |940 (3.2%)           |43 (1.2%)            |214 (2.3%)           |\n\n\n:::\n:::\n\n\n\n\n\nHere is a graph of the same.\n\n\n\n\n\n::: {.cell .column-page-left}\n\n```{.r .cell-code}\ndt_temp_19 <- dt_19 |> select(\n  covid_condition,\n  Trust_in_Science,\n  Trust_in_Politicians,\n  Trust_in_Police,\n  Conspiracy_Beliefs\n)\n\n\n# boxplot dataframe\ndt_long_19 <- pivot_longer(\n  dt_temp_19,\n  cols = -c(\"covid_condition\"),\n  names_prefix = \"Trust_in_\",\n  values_to = \"Values\",\n  names_to = \"Attitudes\"\n) |>\n  drop_na()\n\n\n# make graph\nplot_tab_19 <- dt_long_19 |>\n  ggplot2::ggplot(aes(covid_condition, Values, fill = Attitudes)) +\n  labs(title = \"Institutional Trust and Conspiracy Beliefs (1-7)\",\n       subtitle = \"NZAVS 2019/2020  (N = 42,681)\") +\n  geom_boxplot(size = .05, notch = T) +\n  scale_fill_okabe_ito() +\n  facet_grid (. ~ covid_condition, scales = \"free_x\", space = \"free_x\") +\n  theme(legend.position = \"none\") +\n  labs(x = \"Covid Condition\",\n       y = \"Trust response (1-7)\") +\n  theme_classic()\n\n# graph\nplot_tab_19\n```\n\n::: {.cell-output-display}\n![Boxplot for Institutional Trust: NZAVS Waves During Covid: Years 2020](trust-science_files/figure-html/fig-trust-wave-11-1.png){#fig-trust-wave-11 width=672}\n:::\n:::\n\n\n\n\n\nThis table and graph compare the trust in science, police, and politicians across three different periods: pre-Covid, lockdown, and post-lockdown.\n\nWe observe:\n\n1.  Trust in science increased during the lockdown period and remained higher in the post-lockdown period compared to the pre-Covid period.\n2.  Trust in police remained relatively stable across all three periods, although the trend tracked downward after lockdown.\n3.  Trust in politicians increased during the lockdown period. It decreased slightly in the post-lockdown period but remained higher than in the pre-Covid period.\n4. Conspiracy Beliefs: the average mistrust of official versions of major world events given by authorities appear to decrease during lockdown but subsequently decrease.\n\nNotably, the central tendency may not always be the interesting statistic for understanding social change. There may be greater galvanisation in response that is masked by overall average response.  In future work, we will examine this point.  For now, the trends suggest overall stability during 2019-2020, with increasing confidence in science.  \n\n\n### NZAVS sample responses: years 2019-2022\n\nNext, we examine changes in institutional trust across two waves following the 2019/2020 NZAVS wave. \n\n\nTable:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|echo: false\n#|warning: false\n\n\n# this code creates a table\n# functions to make tables simple\n\nmy.render.cont <- function(x) {\n  with(stats.apply.rounding(stats.default(x), digits=3), c(\"\",\n                                                           \"Mean (SD)\"=sprintf(\"%s (&plusmn; %s)\", MEAN, SD)))\n}\n\nmy.render.cat <- function(x) {\n  c(\"\", sapply(stats.default(x), function(y) with(y,\n                                                  sprintf(\"%d (%0.0f %%)\", FREQ, PCT))))\n}\n\n# now the years \ntab_trust <- table1::table1(\n  ~ Trust_in_Science +\n    Trust_in_Politicians +\n    Trust_in_Police + # not measured in 2019-20\n    Trust_in_Govt_Covid_Response + \n    Conspiracy_Beliefs| Wave,\n  data = dt,\n  overall = FALSE,\n  render.continuous = my.render.cont,\n  render.categorical = my.render.cat\n)\n\n\n# needed for markdown tables\ntab_trust <- data.frame( tab_trust )\n\ntab_trust <- tab_trust |> \n    rename(\"Forms of Institutional Trust\" = X.)\n\n\n# graph\ntab_trust |>\n  kbl(format = \"markdown\", booktabs = TRUE)\n```\n\n::: {.cell-output-display}\n\n\n|Forms of Institutional Trust |X2019                |X2020                |X2021                |\n|:----------------------------|:--------------------|:--------------------|:--------------------|\n|                             |(N=42681)            |(N=42681)            |(N=42681)            |\n|Trust_in_Science             |                     |                     |                     |\n|Mean (SD)                    |5.43 (&plusmn; 1.28) |5.67 (&plusmn; 1.24) |5.70 (&plusmn; 1.26) |\n|Missing                      |375 (0.9%)           |9475 (22.2%)         |14231 (33.3%)        |\n|Trust_in_Politicians         |                     |                     |                     |\n|Mean (SD)                    |3.76 (&plusmn; 1.45) |4.05 (&plusmn; 1.49) |3.92 (&plusmn; 1.56) |\n|Missing                      |853 (2.0%)           |10078 (23.6%)        |15406 (36.1%)        |\n|Trust_in_Police              |                     |                     |                     |\n|Mean (SD)                    |4.58 (&plusmn; 1.26) |4.53 (&plusmn; 1.26) |4.43 (&plusmn; 1.30) |\n|Missing                      |15 (0.0%)            |9378 (22.0%)         |13770 (32.3%)        |\n|Trust_in_Govt_Covid_Response |                     |                     |                     |\n|Mean (SD)                    |NA (&plusmn; NA)     |5.66 (&plusmn; 1.55) |4.79 (&plusmn; 1.94) |\n|Missing                      |42681 (100%)         |9620 (22.5%)         |15123 (35.4%)        |\n|Conspiracy_Beliefs           |                     |                     |                     |\n|Mean (SD)                    |4.36 (&plusmn; 1.63) |4.10 (&plusmn; 1.68) |4.02 (&plusmn; 1.74) |\n|Missing                      |1197 (2.8%)          |9676 (22.7%)         |15110 (35.4%)        |\n\n\n:::\n:::\n\n\n\n\n\nHere is a graph of the same.\n\n\n\n\n\n\n::: {.cell .column-page-left}\n\n```{.r .cell-code}\n# transform data into long formate\ndt_temp <- dt |> select(\n  Wave,\n  Trust_in_Science,\n  Trust_in_Politicians,\n  Trust_in_Police,\n  Trust_in_Govt_Covid_Response, \n  Conspiracy_Beliefs\n)\n\n\n# boxplot dataframe\ndt_long <- pivot_longer(\n  dt_temp,\n  cols = -c(\"Wave\"),\n  names_prefix = \"Trust_in_\",\n  values_to = \"Values\",\n  names_to = \"Attitudes\"\n) |>\n  drop_na()\n\n\n# make graph\nplot_tab <- dt_long |>\n  ggplot2::ggplot(aes(Wave, Values, fill = Attitudes)) +\n  labs(title = \"Institutional Trust and Conspiracy Beliefs\",\n       subtitle = \"NZ 2019/21 to 2021/22 [N = 42,681 (at baseline)]\") +\n  geom_boxplot(size = .05, notch = T) +\n  scale_fill_okabe_ito() +\n  facet_grid (. ~ Wave, scales = \"free_x\", space = \"free_x\") +\n  theme(legend.position = \"none\") +\n  labs(y = \"NZAVS Wave (note: waves cross years)\") + \n  theme_classic()\n\n\nplot_tab\n```\n\n::: {.cell-output-display}\n![Boxplot for Institutional Trust: NZAVS Waves 11-13 (years 2019-2022)](trust-science_files/figure-html/fig-trust-1.png){#fig-trust width=672}\n:::\n:::\n\n\n\n\n\nDescriptive fndings. \n\nTrust in Science: The average trust score increased from 5.43 (±1.28) in 2019 to 5.67 (±1.24) in 2020 and to 5.70 (±1.26) in 2021. The number of missing values increased from 375 (0.9%) in 2019 to 9,475 (22.2%) in 2020 and further to 14,231 (33.3%) in 2021.\n\nTrust in Politicians: The average trust score increased from 3.76 (±1.45) in 2019 to 4.05 (±1.49) in 2020, then slightly decreased to 3.92 (±1.56) in 2021. The number of missing values increased from 853 (2.0%) in 2019 to 10,078 (23.6%) in 2020 and further to 15,406 (36.1%) in 2021.\n\nTrust in Police: The average trust score decreased from 4.58 (±1.26) in 2019 to 4.53 (±1.26) in 2020 and further to 4.43 (±1.30) in 2021. The number of missing values increased from 15 (0.0%) in 2019 to 9,378 (22.0%) in 2020 and further to 13,770 (32.3%) in 2021.\n\nTrust in Government's COVID Response: This metric was not applicable in 2019. The average trust score was 5.66 (±1.55) in 2020 and decreased to 4.79 (±1.94) in 2021. The number of missing values was 42,681 (100%) in 2019, 9,620 (22.5%) in 2020, and 15,123 (35.4%) in 2021.\n\nConspiracy Beliefs: The average score decreased from 4.36 (±1.63) in 2019 to 4.10 (±1.68) in 2020 and further to 4.02 (±1.74) in 2021. The number of missing values increased from 1,197 (2.8%) in 2019 to 9,676 (22.7%) in 2020 and further to 15,110 (35.4%) in 2021.\n\nHow should we in interpret these findings?  Missing data from non-response and panel attrition may bias estimates for the population. We must address bias from missing responses. We address this bias through multiple imputation. \n\n\n\n## Handling missingness\n\nTo handle missing data, we must model and predict missing responses. We attempt two types of missing data imputation. Both use machine learning. The first is the `mlim` package in R, which uses model tuning to optimise the prediction of missing values. The second is the `mice` package in R.  It uses predictive mean matching (ppm) optimse the prediction of missing values.  We find that the mice package/ppm performs better, and present the`ppm` results here. We present the code for both approaches below.\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmc_vv <- readRDS(here::here(push_mods, \"mc_vv\"))\n\n# transform data into long format for graph and table\ndt_temp_mice <- mc_vv |> select(\n  Wave,\n  Trust_in_Science,\n  Trust_in_Politicians,\n  Trust_in_Police,\n  Trust_in_Govt_Covid_Response, \n  Conspiracy_Beliefs\n)\n\n\n# boxplot dataframe\ndt_long_mice <- pivot_longer(\n  dt_temp_mice,\n  cols = -c(\"Wave\"),\n  names_prefix = \"Trust_in_\",\n  values_to = \"Values\",\n  names_to = \"Attitudes\"\n) |>\n  drop_na()\n\nlibrary(ggokabeito)\nplot_tab_mice <- dt_long_mice |>\n  ggplot2::ggplot(aes(Wave, Values, fill = Attitudes)) +\n  labs(title = \"Institutional Trust and Conspiracy Beliefs: Missingness Multiply-Imputed\",\n       subtitle = \"NZ 2019/21 to 2021/22 [N = 42,681 (at baseline)]\") +\n  geom_boxplot(size = .05, notch = T) +\n  scale_fill_okabe_ito() +\n  facet_grid (. ~ Wave, scales = \"free_x\", space = \"free_x\") +\n  theme(legend.position = \"none\") +\n  labs(y = \"NZAVS Wave (note: waves cross years)\") + \n  theme_classic()\n\n\nplot_tab_mice\n```\n\n::: {.cell-output-display}\n![](trust-science_files/figure-html/ppm-graph-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmc_vv <- readRDS(here::here(push_mods, \"mc_vv\"))\n# now the years \ntab_trust_mice <- table1::table1(\n  ~ Trust_in_Science +\n    Trust_in_Politicians +\n    Trust_in_Police + # not measured in 2019-20\n    Trust_in_Govt_Covid_Response + \n    Conspiracy_Beliefs| Wave,\n  data = mc_vv,\n  overall = FALSE,\n  render.continuous = my.render.cont,\n  render.categorical = my.render.cat\n)\n\n\n\n# must be a data frame\ntab_trust_mice <- data.frame(tab_trust_mice)\n\ntab_trust_mice <- tab_trust_mice |> \n    dplyr::rename(\"Forms of Institutional Trust\" = X.)\n\n# graph\ntab_trust_mice |>\n  kbl(format = \"markdown\", booktabs = TRUE)\n```\n\n::: {.cell-output-display}\n\n\n|Forms of Institutional Trust |X2019                |X2020                |X2021                |\n|:----------------------------|:--------------------|:--------------------|:--------------------|\n|                             |(N=469491)           |(N=469491)           |(N=469491)           |\n|Trust_in_Science             |                     |                     |                     |\n|Mean (SD)                    |5.43 (&plusmn; 1.28) |5.64 (&plusmn; 1.25) |5.65 (&plusmn; 1.28) |\n|Missing                      |375 (0.1%)           |9475 (2.0%)          |14231 (3.0%)         |\n|Trust_in_Politicians         |                     |                     |                     |\n|Mean (SD)                    |3.76 (&plusmn; 1.45) |4.02 (&plusmn; 1.50) |3.85 (&plusmn; 1.57) |\n|Missing                      |853 (0.2%)           |10078 (2.1%)         |15406 (3.3%)         |\n|Trust_in_Police              |                     |                     |                     |\n|Mean (SD)                    |4.58 (&plusmn; 1.26) |4.50 (&plusmn; 1.27) |4.37 (&plusmn; 1.32) |\n|Missing                      |15 (0.0%)            |9378 (2.0%)          |13770 (2.9%)         |\n|Trust_in_Govt_Covid_Response |                     |                     |                     |\n|Mean (SD)                    |NA (&plusmn; NA)     |5.64 (&plusmn; 1.56) |4.74 (&plusmn; 1.96) |\n|Missing                      |469491 (100%)        |9620 (2.0%)          |15123 (3.2%)         |\n|Conspiracy_Beliefs           |                     |                     |                     |\n|Mean (SD)                    |4.36 (&plusmn; 1.63) |4.13 (&plusmn; 1.68) |4.06 (&plusmn; 1.75) |\n|Missing                      |1197 (0.3%)          |9676 (2.1%)          |15110 (3.2%)         |\n\n\n:::\n:::\n\n\n\n\n\nThe imputed data contain ten imputed datasets plus the original data with missing values.  We will need to adjust for the uncertainities of multiple imputation using Rubin's rule.\n\nAdditionally, we are now grouping pre and post responses together in the 2019 wave. So we are no longer identifying specific responses of to the COVID pandemic and response. To identify the specific effects of the COVID pandemic and response requires care. There are no contrasts from which to derive comparisons. That is, because all in the population were subject to the exposure, we cannot straightforwardly infer how people would have responded were they not exposed. We will return to this issue in future work.\n\nThese provisos aside, we find evidence for continued average confidence in science, with some evidence for a continued downward shift in trust for the NZ police. \n\nNext, we formally model change over time using generalised estimating equations (GEE).  They models take into account uncertainties from multiple imputation. We employ survey weights to recover population estimates. \n\n### Results for average responses. \n\n\n### Trust in science\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell tbl-cap='Trust in Science by NZAVS Wave'}\n\n```{.r .cell-code}\n# read output for table\npooled_m_trust_in_science <- readRDS( here::here(push_mods, \"pooled_m_trust_in_science\"))\n\nsummary( pooled_m_trust_in_science ) |> \n  as.data.frame()|> \n  kbl(format = \"markdown\", digits = 3, caption = \"Trust in Science by NZAVS Wave\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Trust in Science by NZAVS Wave\n\n|term        | estimate| std.error| statistic|        df| p.value|\n|:-----------|--------:|---------:|---------:|---------:|-------:|\n|(Intercept) |    5.451|     0.007|   756.404| 62762.541|       0|\n|Wave2020    |    0.192|     0.006|    29.781|   176.552|       0|\n|Wave2021    |    0.215|     0.007|    29.572|   146.591|       0|\n\n\n:::\n:::\n\n::: {.cell tbl-cap='Trust in Politicians by NZAVS Wave'}\n\n```{.r .cell-code}\n# read output for table\npooled_m_trust_in_politicians <- readRDS( here::here(push_mods, \"pooled_m_trust_in_politicians\"))\n\n \nsummary( pooled_m_trust_in_politicians ) |> \n  as.data.frame()|> \n  kbl(format = \"markdown\", digits = 3,  caption = \"Trust in Politicians by NZAVS Wave\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Trust in Politicians by NZAVS Wave\n\n|term        | estimate| std.error| statistic|        df| p.value|\n|:-----------|--------:|---------:|---------:|---------:|-------:|\n|(Intercept) |    3.736|     0.008|   441.327| 14871.025|       0|\n|Wave2020    |    0.251|     0.009|    28.251|    93.102|       0|\n|Wave2021    |    0.080|     0.009|     8.803|   259.975|       0|\n\n\n:::\n:::\n\n::: {.cell tbl-cap='Trust in Police by NZAVS Wave'}\n\n```{.r .cell-code}\n# read output for table\npooled_m_trust_in_police <- readRDS( here::here(push_mods, \"pooled_m_trust_in_police\"))\n\n \nsummary( pooled_m_trust_in_police ) |> \n  as.data.frame()|> \n  kbl(format = \"markdown\", digits = 3,  caption = \"Trust in Police by NZAVS Wave\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Trust in Police by NZAVS Wave\n\n|term        | estimate| std.error| statistic|         df| p.value|\n|:-----------|--------:|---------:|---------:|----------:|-------:|\n|(Intercept) |    4.539|     0.008|   574.900| 103491.441|       0|\n|Wave2020    |   -0.110|     0.007|   -16.752|    111.240|       0|\n|Wave2021    |   -0.247|     0.008|   -31.849|    133.079|       0|\n\n\n:::\n:::\n\n::: {.cell tbl-cap='Trust in Science by NZAVS Wave'}\n\n```{.r .cell-code}\n# read output for table\npooled_m_trust_in_gov_covid <- readRDS( here::here(push_mods, \"pooled_m_trust_in_gov_covid\"))\n\nsummary( pooled_m_trust_in_gov_covid ) |> \n  as.data.frame()|> \n  kbl(format = \"markdown\", digits = 3, caption = \"Trust in Covid Governemnt Response by NZAVS Wave\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Trust in Covid Governemnt Response by NZAVS Wave\n\n|term        | estimate| std.error| statistic|      df| p.value|\n|:-----------|--------:|---------:|---------:|-------:|-------:|\n|(Intercept) |    5.614|     0.011|   523.237| 103.496|       0|\n|Wave2021    |   -0.903|     0.011|   -81.429|  67.518|       0|\n\n\n:::\n:::\n\n::: {.cell tbl-cap='Conspiracy Beliefs by NZAVS Wave'}\n\n```{.r .cell-code}\n# read output for table\npooled_m_conspiracy_beliefs <- readRDS(  here::here(push_mods, \"pooled_m_conspiracy_beliefs\"))\n\nsummary(pooled_m_conspiracy_beliefs) |> \n  as.data.frame()|> \n  kbl(format = \"markdown\", digits = 3, caption =  \"Conspiracy Beliefs by NZAVS Wave\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Conspiracy Beliefs by NZAVS Wave\n\n|term        | estimate| std.error| statistic|       df| p.value|\n|:-----------|--------:|---------:|---------:|--------:|-------:|\n|(Intercept) |    4.362|     0.009|   464.975| 4101.840|       0|\n|Wave2020    |   -0.251|     0.012|   -20.768|   49.163|       0|\n|Wave2021    |   -0.308|     0.013|   -23.368|   48.228|       0|\n\n\n:::\n:::\n\n\n\n\n\n\nThe results reflect findings in the descriptiove tables. \n\n\n#### Trust in Science by NZAVS Wave:\n\n- From 2019 to 2020, trust in science reliably increased (estimate = 0.192, p < 0.001).\n- From 2019 to 2021, trust in science also reliably increased (estimate = 0.215, p < 0.001).\n\nThere is no downward trend in average Trust in Science. \n\n\n\n#### Trust in Politicians by NZAVS Wave:\n\n- From 2019 to 2020, the increase in trust in politicians was reliable (estimate = 0.251, p < 0.001).\n- From 2019 to 2021, the increase in trust in politicians was also reliable (estimate = 0.080, p < 0.001).\n\nComparisons here are with the baseline wave, comparing 2019 and 2021 we find evidence for regression to the baseline wave. Whereas trust in politicians increased during the initial COVID-19 attack and response, gains to average trust appear to have been dropping. \n\n\n#### Trust in Police by NZAVS Wave:\n\n- From 2019 to 2020, the decrease in trust in police was reliable (estimate = -0.110, p < 0.001).\n- From 2019 to 2021, the decrease in trust in police was also reliable (estimate = -0.247, p < 0.001).\n\nHere we find evidence for declining Trust in the NZ police. Notably, however, overall levels of Trust in the NZ police remain high. \n\n#### Trust in Government COVID Response by NZAVS Wave (only two waves):\n\n- From 2019 to 2021, the decrease in trust in the NZ government's COVID response was reliable (estimate = -0.903, p < 0.001). This represents a major drop in confidence. Notably, this drop in confidence for the NZ government's COVID response has not considerably affected attitudes to science. \n\n#### Conspiracy Beliefs:\n\n- From 2019 to 2020, the decrease in conspiracy beliefs was reliable (estimate = -0.251, p < 0.001).\n- From 2019 to 2021, the decrease in conspiracy beliefs was also reliable (estimate = -0.308, p < 0.001).\n\nOn average, we find that conspiracy beliefs are falling. However, this evidence is based on the assumptions that the model we have used impute missing conspiracy beliefs is adequate. It is possible that real change in conspiracy beliefs, and indeed for all imputed variables differs from what we have recovered in the imputation model. \n\n\n### Summary\n\nThe results indicate a reliable increase in trust in science from 2019 to 2020, and that this shift has remained constant. In contrast, changes in trust in politicians, trust in police, trust in the government's COVID response, across the waves were generally unreliable.  Evidence suggests that average conspiracy beliefs may have declined.   \n\n\nThe preliminary findings merit further research. \n\nFirstly, multiple imputation models rely on assumptions. These assumptions must be tested. \n\nSecondly, when a population becomes more polarized, the average response may be misleading, potentially indicating no change. We must investigate change at the margins of reponse, not merely at the average response. \n\nThirdly, we need not assume that the items model a univariate latent construct. We might instead model items from the scales individually, as suggested by @vanderweele2022.\n\nIn the near future, that address these challenges. Stay tuned!  \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n### Information about the New Zealand Attitudes and Values Study.\n\nFor more information about the NZAVS see: [here](https://www.psych.auckland.ac.nz/en/about/new-zealand-attitudes-and-values-study.html) and [here](https://go-bayes.github.io/reports/posts/nzavs/)\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
    "supporting": [
      "trust-science_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}